---
- hosts: servers
  become: true

  roles:
    - { role: common, tags: ["common"] }
    - { role: docker, tags: ["docker"] }
    - { role: jenkins, tags: ["jenkins"] }
    - { role: nexus, tags: ["nexus"] }
    - { role: nginx, tags: ["nginx"] }